export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";
export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SHOW_PRODUCT = "SET_SHOW_PRODUCT";
export const FETCH_PRODUCTS_BY_FILTER = "FETCH_PRODUCTS_BY_FILTER";
export const INIT_PRODUCTS = "INIT_PRODUCTS";

export const SET_SHOW_BRAND = 'SET_SHOW_BRAND';
export const INIT_BRANDS = 'INIT_BRANDS';
export const SET_BRANDS = 'SET_BRANDS';
export const FETCH_BRANDS_FAILED = "FETCH_BRANDS_FAILED";

export const START_FETCH_CART = 'START_FETCH_CART';
export const ADD_PRODUCT_TO_CART = "ADD_SIZE_TO_CART"
export const ADD_PRODUCT_TO_CART_FAILED = "ADD_PRODUCT_TO_CART_FAILED"
export const ADD_CART_TO_FAVORITE = "ADD_CART_TO_FAVORITE"
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART"
export const UPDATE_CART_PRODUCT_SIZE = "UPDATE_CART_PRODUCT_SIZE"
export const UPDATE_CART_PRODUCT_QTY = "UPDATE_CART_PRODUCT_QTY"
export const FETCH_CART_FAILED = "FETCH_CART_FAILED"
export const REFRESH_CART = "REFRESH_CART"
export const SET_CART = "SET_CART"

export const INIT_ORDER = "INIT_ORDER";
export const START_ORDER= "START_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const ORDER_FAILED= "ORDER_FAILED";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const FETCH_ORDER_SUCCESS = "FETCH_ORDER_SUCCESS"
 
export const DELETE_FAVORITE = "DELETE_FAVORITE";
export const CREATE_FAVORITE = "CREATE_FAVORITE";
export const INIT_FAVORITES = "INIT_FAVORITES"
export const SET_FAVORITES = "SET_FAVORITES"
export const FETCH_FAVORITES_FAILED = "FETCH_FAVORITES_FAILED"
export const START_FETCH_FAVORITES = "START_FETCH_FAVORITES"
export const ADD_FAVORITE_TO_CART = "ADD_FAVORITE_TO_CART"

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL'
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

export const USER_PLAN_START = 'USER_PLAN_START'
export const USER_PLAN_SUCCESS = 'USER_PLAN_SUCCESS'
export const INIT_PLAN_MEMBERSHIP = 'INIT_PLAN_MEMBERSHIP'
export const USER_PLAN_FAIL = 'USER_PLAN_FAIL'
export const USER_PLAN_DELETE = 'USER_PLAN_DELETE'
export const FETCH_PLANS_SUCCESS = 'FETCH_PLANS_SUCCESS'
export const FETCH_PLANS_FAIL = 'FETCH_PLANS_FAIL'
export const FETCH_PLANS_START = 'FETCH_PLANS_START'
export const INIT_FETCH_PLANS = 'INIT_FETCH_PLANS'